#普通数据的配置
name: zhangsan
#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing
#行内对象的配置
person1: {name: zhangsan,age: 18,addr: beijing}
server:
  port: 8082
#配置数组/集合(普通字符串)
city:
  - beijing
  - tianjin
  - henan
  - hebei
city1: [beijing,shanghao,shengzhen]
#配置数组/集合(对象)
student:
  - name: tom
    age: 18
  - name: lucy
    age: 20

stuent1: [{name: jack,age: 12},{name: tom,age: 10}]

#map配置
map:
  key1: value1
  key2: value2